ACNA-2839 | Added Update Template Endpoint
adobe/adp-template-registry-api pull request #31
Opened 2024-04-12 05:17 UTC by amulyakashyap09

## Description

New endpoint for updating an existing template. This will be a new action in the service and it should be at the path PUT /templates/{templateId}

If the template does not exist, throw a 404 error.

## Endpoint behavior

1. Look to see if the passed template has credentials or apis
2. If present, just overwrite the passed request body as the new template
3. If not present, look for links.consoleProject and call the new /install-config endpoint for the project projectId. Add the returned api and credential config to the new template record
4. Add the new endpoint to openapi.yml definitions 

We'll also need to make sure the request body can handle the updatedBy field, that includes the username of the user who updated the template.

This endpoint should be protected by IMS auth and the t`emplate_registry.write scope`

## Proposal for update template endpoint

https://wiki.corp.adobe.com/display/ioarch/Proposal%3A+Expand+Template+Registry+to+support+Console+Templates#Proposal:ExpandTemplateRegistrytosupportConsoleTemplates-Updatetemplate

## Related Issue

[ACNA-2839](https://jira.corp.adobe.com/browse/ACNA-2839)

## Motivation and Context

## How Has This Been Tested?

Locally on machine via unit-tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-04-12 10:50 UTC, arjuncooliitr commented on template-registry-api.json
> +          "description": "The name of the template on npmjs.com",
Is templateId same as templateName? Else the description should say Id

2024-04-12 10:50 UTC, arjuncooliitr commented on template-registry-api.json
> +              "description": "The name of the user who created the template",
Should be name of the user who updated

2024-04-13 09:58 UTC, shazron commented
@amulyakashyap09 Tests are not passing.

2024-05-01 14:00 UTC, MichaelGoberling requested changes

2024-05-01 14:00 UTC, MichaelGoberling commented on template-registry-api.json
> +          "action": "templates-post.http",
needs to be templates-put.http

2024-05-01 14:00 UTC, MichaelGoberling commented on template-registry-api.json
> +    "/templates/{templateId}": {
getting the following error when linting this spec: 

```
Paths should resolve unambiguously. Found two ambiguous paths: `/templates/{templateId}` and `/templates/{templateName}`.
```

2024-05-01 14:00 UTC, MichaelGoberling commented on actions/templates/put/index.js
> +    const accessToken = getBearerToken(params);
access token validation is done at the runtime level now based on our swagger security definition, no need to validate again here

2024-05-07 14:12 UTC, MichaelGoberling approved these changes
LGTM besides one minor debug console log

2024-05-07 14:12 UTC, MichaelGoberling commented on actions/templates/delete/index.js
> +    console.trace(error);
remove, `logger.error(error)` should capture what we need below

2024-05-08 07:38 UTC, merged